### PR TITLE
WIP: Affinity groups

### PR DESCRIPTION
**Pull request by fern4lvarez**
**Do not merge**

PR created for code review purposes.

https://issues.apache.org/jira/browse/LIBCLOUD-671

### CODE REVIEW

**Comment by sfriesel** [comment]
Can you link the libcloud issue in the pr description?

**Comment by fern4lvarez** [comment]
We didn't create it yet.

**Comment by fern4lvarez** [comment]
https://issues.apache.org/jira/browse/LIBCLOUD-671

**Comment by TooAngel** [comment]
PR LGTM

**Comment by fern4lvarez** [comment]
https://github.com/apache/libcloud/pull/468

**Comment by sfriesel** [comment]
can this be closed now? or merged?

**Pull request closed without merging**
